#
# PlanetLab RPM generation
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2003-2006 The Trustees of Princeton University
#
# $Id: Makefile,v 1.84 2006/02/22 21:42:37 mlhuang Exp $
#

# Default target
all:

# Default values. If TAG is HEAD, a %{date} variable will be defined
# in the generated spec file.
TAG := HEAD
CVSROOT := :pserver:anon@cvs.planet-lab.org:/cvs
RPMBUILD := rpmbuild
CVS_RSH := ssh

# By default, the naming convention for built RPMS is
# <name>-<version>-<release>.<PLDISTRO>.<arch>.rpm
# Set PLDISTRO on the command line to differentiate between downstream
# variants.
PLDISTRO := planetlab

include $(PLDISTRO).mk

ifeq ($(findstring $(package),$(ALL)),)

# Build all packages
all: $(ALL)

# Recurse
$(ALL):
	$(MAKE) package=$@

# Remove files generated by this package
$(foreach package,$(ALL),$(package)-clean): %-clean:
	$(MAKE) package=$* clean

# Remove all generated files
clean:
	rm -rf BUILD RPMS SOURCES SPECS SRPMS .rpmmacros tmp parseSpec

.PHONY: all $(ALL) $(foreach package,$(ALL),$(package)-clean) clean

else

# Define variables for Rules.mk
CVSROOT := $(if $($(package)-CVSROOT),$($(package)-CVSROOT),$(CVSROOT))
TAG := $(if $($(package)-TAG),$($(package)-TAG),$(TAG))
MODULE := $($(package)-MODULE)
SPEC := $($(package)-SPEC)
RPMFLAGS := $($(package)-RPMFLAGS)
RPMBUILD := $(if $($(package)-RPMBUILD),$($(package)-RPMBUILD),$(RPMBUILD))
CVS_RSH := $(if $($(package)-CVS_RSH),$($(package)-CVS_RSH),$(CVS_RSH))

include Rules.mk

endif
